apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapper
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        service: webapper
    spec:
      containers:
      - name: webapper
        image: rchicoli/webapper:latest
        ports:
        - name: webservice
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "120Mi"
            cpu: "250m"
          limits:
            memory: "150Mi"
            cpu: "500m"
status:
  conditions:
  - type: Progressing
    status: "False"
    reason: progressDeadlineExceeded
