apiVersion: v1
kind: Service
metadata:
  labels:
    service: webapper
  name: webapper
spec:
  ports:
  - name: webservice
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: webapper
status:
  loadBalancer: {}