apiVersion: v1
kind: Service
metadata:
  labels:
    service: webapper
  name: webapper
spec:
  ports:
  - name: webservice
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: "LoadBalancer"
  selector:
    service: webapper
status:
  loadBalancer: {}
