---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: non-existent

images:
- name: rchicoli/webapper
  newTag: 1.1.1

resources:
- service.yaml
- ingress.yaml
- poddisruptionbudget.yaml
- deployment.yaml

configurations:
- commonLabels.yaml

commonLabels:
  app.kubernetes.io/maintainer: rchicoli
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: webapper
  app.kubernetes.io/version: 1.1.1
  app.kubernetes.io/part-of: operations

generatorOptions:
  disableNameSuffixHash: true
